version: "3"

services:
  nginx:
    build:
      context: ./containers/nginx
      dockerfile: Dockerfile
      args:
        - SERVER_NAME=${SERVER_NAME}
        - DOCROOT=/var/www/${DRUPAL_PROJECT_FOLDER}/web
    ports:
      - "${NGINX_PORT}:443"
    volumes:
      - ./www/${DRUPAL_PROJECT_FOLDER}:/var/www/${DRUPAL_PROJECT_FOLDER}
    links:
      - php
      - db
    command: /bin/bash -c "nginx -g 'daemon off;'"

  php:
    build:
      context: ./containers/php
      dockerfile: Dockerfile
      args:
        - PHP_TAG=${PHP_TAG:-7.4.14-fpm-buster}
    volumes:
      - ./www/${DRUPAL_PROJECT_FOLDER}:/var/www/${DRUPAL_PROJECT_FOLDER}
      - ./data/tmp/php:/tmp
    working_dir: /var/www/${DRUPAL_PROJECT_FOLDER}

  db:
    build:
      context: ./containers/mariadb
      dockerfile: Dockerfile
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/tmp/db:/tmp
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
