version: '3'

services:
  web:
    build:
      context: ./container/web
      dockerfile: Dockerfile
      args:
        - DOCROOT_FOLDER=${DOCROOT_FOLDER}
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  db:
    build:
      context: ./container/db
      dockerfile: Dockerfile
    restart: always
    ports:
        - "3306:3306"
    volumes:
      - ./db-files:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
