version: '3'

services:
  web:
    build:
      context: ./container/web
      dockerfile: Dockerfile.php-${PHP_VERSION}
      args:
        - DOCROOT_FOLDER=/var/www/${DOCROOT_PATH}
        - WORKDIR=/var/www/${WORKDIR}
    restart: always
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./www/${PROJECT_FOLDER_NAME}:/var/www/${PROJECT_FOLDER_NAME}
      - ./container/web/conf/php/${PHP_VERSION}/etc/php.ini:/etc/php.ini

  varnish:
    build:
      context: ./container/varnish
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${VARNISH_PORT}:80"
    volumes:
      - ./container/varnish/conf/varnish.params:/etc/varnish/varnish.params
      - ./container/varnish/conf/default.vcl:/etc/varnish/default.vcl

  nginx:
    build:
      context: ./container/nginx
      args:
        - SERVER_NAME=${SERVER_NAME}
    restart: always
    ports:
      - "${NGINX_PORT}:443"
    command: /bin/bash -c "nginx -g 'daemon off;'"

  db:
    build:
      context: ./container/db
      dockerfile: Dockerfile.${MARIADB_VERSION}
    # container_name: db
    restart: always
    ports:
        - "${DB_PORT}:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./db-dump:/tmp
      - ./container/db/conf/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

  # solr:
  #   build:
  #     context: ./container/solr/${SOLR_VERSION}
  #     dockerfile: Dockerfile
  #   container_name: solr
  #   restart: always
  #   ports:
  #     - "${SOLR_PORT}:8983"
