version: '3'

services:
  web:
    build:
      context: ./container/web
      dockerfile: Dockerfile.php-${PHP_VERSION}
      args:
        - DOCROOT_FOLDER=${DOCROOT_FOLDER}
    container_name: web
    restart: always
    volumes:
      - ./www:/var/www/html
      - ./container/web/conf/php/${PHP_VERSION}/etc/php.ini:/etc/php.ini

  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: db
    restart: always
    ports:
        - "3306:3306"
    volumes:
      - ./db-files:/var/lib/mysql
      - ./db-dump:/tmp
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8888:8080

  varnish:
    build:
      context: ./container/varnish
      dockerfile: Dockerfile
    container_name: varnish
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./container/varnish/conf/varnish.params:/etc/varnish/varnish.params
      - ./container/varnish/conf/default.vcl:/etc/varnish/default.vcl

  nginx:
    build:
      context: ./container/nginx
      args:
        - SERVER_NAME=${SERVER_NAME}
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    command: /bin/bash -c "nginx -g 'daemon off;'"

  solr:
    build:
      context: ./container/solr/${SOLR_VERSION}
      dockerfile: Dockerfile
    container_name: solr
    restart: always
    ports:
      - "8983:8983"
