version: '3'

services:
  web:
    build:
      context: ./container/web
      dockerfile: Dockerfile.php-${PHP_VERSION}
      args:
        - DOCROOT_FOLDER=${DOCROOT_FOLDER}
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./container/web/conf/php/${PHP_VERSION}/etc/php.ini:/etc/php.ini

  db:
    build:
      context: ./container/db
      dockerfile: Dockerfile
    restart: always
    ports:
        - "3306:3306"
    volumes:
      - ./db-files:/var/lib/mysql
      - ./db-dump:/tmp
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  varnish:
    build:
      context: ./container/varnish
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./container/varnish/conf/varnish.params:/etc/varnish/varnish.params
      - ./container/varnish/conf/default.vcl:/etc/varnish/default.vcl
