FROM centos:7

LABEL maintainer.name="Chhabi Pachabhaiya" \
      maintainer.email="chhabi@pachabhaiya.com" \
      version="1.0" \
      description="PHP-FPM 7.2 and Apache 2.4 in CentOS 7."

ARG DOCROOT_FOLDER=/var/www/html
ENV DOCROOT_FOLDER=${DOCROOT_FOLDER}

# Update all packages.
RUN yum update -y

# Install the EPEL repository.
RUN yum install epel-release -y

# Install Apache HTTP server.
RUN yum install httpd -y

# Install mod_ssl module.
RUN yum install mod_ssl -y

# "envsubst" command is available after installing "gettext" package.
# This is needed to substitue the environment variables.
RUN yum install gettext -y

# Install repository auto-configuration package for Enterprise Linux 7.
RUN yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y

# Enable remi-php72 repository.
RUN yum-config-manager --enable remi-php72

# Install php-fpm and additional packages required for Drupal.
RUN yum install php-fpm php-mysql php-pdo php-gd php-mbstring php-opcache php-xml php-mcrypt -y

# Install supervisor package. This is needed to run multiple services
# in a single container.
RUN yum install supervisor -y

# Install additional packages needed for Drush to work.
# Drush does not work if database server is not installed in web container
RUN yum install mariadb drush git wget -y
RUN wget -P /tmp https://github.com/drush-ops/drush/releases/download/8.1.16/drush.phar
RUN chmod a+x /tmp/drush.phar
RUN mv /tmp/drush.phar /usr/local/bin/drush

# Install composer.
RUN yum install zip unzip -y
RUN wget -P /usr/local/bin https://getcomposer.org/download/1.8.4/composer.phar
RUN chmod a+x /usr/local/bin/composer.phar
RUN ln -s /usr/local/bin/composer.phar /usr/local/bin/composer

RUN mkdir /var/run/php-fpm
RUN chmod 755 /var/run/php-fpm

# Make a copy of original configuration files.
RUN cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.original
RUN cp /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.original
RUN cp /etc/httpd/conf.modules.d/00-mpm.conf /etc/httpd/conf.modules.d/00-mpm.conf.original
RUN cp /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.conf.original

# Copy configuration files from host to container.
COPY conf/apache/etc/httpd/conf/httpd.conf /etc/httpd/conf/
COPY conf/apache/etc/httpd/conf.d/httpd-vhosts.conf.template /etc/httpd/conf.d/
COPY conf/apache/etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/
COPY conf/apache/etc/httpd/conf.modules.d/00-mpm.conf /etc/httpd/conf.modules.d/
COPY conf/apache/etc/httpd/conf.d/php.conf /etc/httpd/conf.d/
COPY conf/php/7.2/etc/php-fpm.d/www.conf /etc/php-fpm.d/
COPY conf/supervisor/supervisord.conf /etc/

# Substitute environment variables.
RUN envsubst '$${DOCROOT_FOLDER}' < /etc/httpd/conf.d/httpd-vhosts.conf.template > /etc/httpd/conf.d/httpd-vhosts.conf

WORKDIR ${DOCROOT_FOLDER}

EXPOSE 80 443

ADD ./scripts /scripts
RUN chmod 755 /scripts/*

CMD ["/bin/bash", "/scripts/start.sh"]
